# Generated by Django 3.2 on 2021-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('ID_candidate', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Surname', models.TextField()),
            ],
        ),
    ]
