# Generated by Django 3.2 on 2021-05-27 22:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='Workers_ID_Worker',
            new_name='ID_Workers',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='Candidate_present',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='Candidates_ID_Candidate',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='Recruitment_Meetings_ID',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='Tests_ID',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='Worker_present',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='ID_Candidates_Role',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='Stage',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='ID_Candidates_Role',
        ),
        migrations.AddField(
            model_name='calendar',
            name='Meeting_type',
            field=models.CharField(choices=[('T', 'Test'), ('T', 'Job interview')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='recruitment_meetings',
            name='ID_Workers',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.workers', verbose_name='Worker'),
        ),
        migrations.AddField(
            model_name='tests',
            name='Check_out_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tests',
            name='ID_Workers',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.workers'),
        ),
        migrations.CreateModel(
            name='Recruitment_Process',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Stage', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='', max_length=1)),
                ('ID_Candidates', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.candidates', verbose_name='Candidate')),
                ('ID_Candidates_Role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.candidates_role')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Recruitment process',
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='ID_Recruitment_Process',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.recruitment_process', verbose_name='Recruitment process'),
        ),
        migrations.AddField(
            model_name='recruitment_meetings',
            name='ID_Recruitment_Process',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.recruitment_process', verbose_name='Recruitment process'),
        ),
        migrations.AddField(
            model_name='tests',
            name='ID_Recruitment_Process',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.recruitment_process', verbose_name='Recruitment process'),
        ),
    ]
