# Generated by Django 3.2 on 2021-05-28 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20210527_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment_meetings',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Meeting_date',
            field=models.DateTimeField(),
        ),
    ]
