# Generated by Django 3.2 on 2021-05-30 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20210528_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitment_process',
            options={'verbose_name': 'Process', 'verbose_name_plural': 'Recruitment process'},
        ),
        migrations.AlterField(
            model_name='recruitment_process',
            name='ID_Candidates_Role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.candidates_role', verbose_name='Candidate role'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='ID_Recruitment_Process',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.recruitment_process', verbose_name='Candidate and his role'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='ID_Workers',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.workers', verbose_name='Worker'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='ID_Workers_Role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.workers_role', verbose_name='Role'),
        ),
    ]
