# Generated by Django 3.2 on 2021-05-16 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_alter_candidates_application_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates_Role',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='ID_candidate',
            new_name='ID',
        ),
        migrations.AddField(
            model_name='candidates',
            name='CV',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='candidates',
            name='Email_address',
            field=models.EmailField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='Hired',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='candidates',
            name='Motivation_letter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='candidates',
            name='Phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='Sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='Stage',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Application_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Birthdate',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='candidates',
            name='ID_Candidates_Role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.candidates_role'),
        ),
    ]
