# Generated by Django 3.2.1 on 2021-06-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_auto_20210530_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='Cancel_reason',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='Meeting_status',
            field=models.CharField(choices=[('P', 'Upcoming'), ('C', 'Cancelled'), ('N', 'Confirmed')], default='U', max_length=1),
        ),
    ]
