# Generated by Django 3.2.1 on 2021-09-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_auto_20210613_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Meeting_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Meeting_type',
            field=models.CharField(choices=[('T', 'Test'), ('R', 'Job interview')], default=None, max_length=1, null=True),
        ),
    ]
