# Generated by Django 3.2 on 2021-05-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_auto_20210516_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers_Role',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(default='', null=True)),
                ('Surname', models.TextField(default='', null=True)),
                ('Birthdate', models.DateField(null=True)),
                ('Login', models.CharField(max_length=32, null=True)),
                ('Password', models.CharField(default='', max_length=32)),
                ('Email_addres', models.EmailField(max_length=50, null=True)),
                ('ID_Workers_Role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.workers_role')),
            ],
        ),
    ]
