# Generated by Django 3.2.1 on 2021-09-07 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Site', '0006_auto_20210907_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='Login',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='Password',
        ),
        migrations.AddField(
            model_name='workers',
            name='ID_User',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
