# Generated by Django 3.2 on 2021-05-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_workers_workers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers_role',
            name='Name',
            field=models.TextField(default='', unique=True),
        ),
    ]
