# Generated by Django 3.2.1 on 2021-09-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_auto_20210907_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='Meeting_date',
            field=models.DateTimeField(),
        ),
    ]
