# Generated by Django 3.2 on 2021-05-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_alter_workers_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment_Meetings',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Hard_skills', models.TextField(default='', null=True)),
                ('Soft_skills', models.TextField(default='', null=True)),
                ('Grade', models.IntegerField()),
                ('Notes', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Points', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'Workers', 'verbose_name_plural': 'Worker'},
        ),
        migrations.AlterModelOptions(
            name='workers_role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'Workers roles'},
        ),
        migrations.AlterField(
            model_name='workers',
            name='Name',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='Surname',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='workers_role',
            name='Name',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Meeting_date', models.DateField()),
                ('Description', models.TextField(default='', null=True)),
                ('Stage', models.CharField(default='1', max_length=1)),
                ('Candidates_ID_Candidate', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.candidates')),
                ('Recruitment_Meetings_ID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.recruitment_meetings')),
                ('Tests_ID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.tests')),
                ('Workers_ID_Worker', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.workers')),
            ],
        ),
    ]
