# Generated by Django 3.2 on 2021-09-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_alter_recruitment_process_id_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment_meetings',
            name='ID_Recruitment_Process',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.recruitment_process', verbose_name='Recruitment process'),
        ),
    ]
