# Generated by Django 3.2 on 2021-05-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_auto_20210524_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='ID_Candidates_Role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.candidates_role'),
        ),
    ]
