# Generated by Django 3.2.4 on 2021-09-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_auto_20210920_1526'),
        ('Site', '0010_alter_recruitment_meetings_id_recruitment_process'),
    ]

    operations = [
    ]
