# Generated by Django 3.2 on 2021-05-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_tests_id_candidates_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='ID_Candidates',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.candidates'),
        ),
    ]
