# Generated by Django 3.2 on 2021-05-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_tests_id_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='ID_Candidates',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Site.candidates'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='ID_Candidates_Role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Site.candidates_role'),
        ),
    ]
