# Generated by Django 3.2 on 2021-05-26 09:55

import Site.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_auto_20210524_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'event', 'verbose_name_plural': 'Calendar'},
        ),
        migrations.AlterModelOptions(
            name='candidates',
            options={'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='candidates_role',
            options={'verbose_name': 'Candidate role', 'verbose_name_plural': 'Candidates roles'},
        ),
        migrations.AlterModelOptions(
            name='recruitment_meetings',
            options={'verbose_name': 'meeting', 'verbose_name_plural': 'Recruitment meetings'},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'verbose_name': 'test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AlterModelOptions(
            name='workers_role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Workers roles'},
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='Stage',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='ID_Candidates',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Candidates_ID_Candidate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.candidates', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Recruitment_Meetings_ID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.recruitment_meetings', verbose_name='Worker'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Tests_ID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.tests', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Hired',
            field=models.CharField(choices=[(Site.models.hired_choice['in_process'], 'In process'), (Site.models.hired_choice['yes'], 'Yes'), (Site.models.hired_choice['no'], 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Sex',
            field=models.CharField(choices=[(Site.models.sex_choice['Man'], 'Man'), (Site.models.sex_choice['Woman'], 'Woman')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Stage',
            field=models.CharField(choices=[(Site.models.stage_choice['first'], 'first'), (Site.models.stage_choice['second'], 'second'), (Site.models.stage_choice['third'], 'third')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Surname',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='candidates_role',
            name='Name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='recruitment_meetings',
            name='Grade',
            field=models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tests',
            name='ID_Candidates_Role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Site.candidates_role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='Points',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
