# Generated by Django 3.2 on 2021-05-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0013_auto_20210526_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='Hired',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Stage',
            field=models.CharField(default='', max_length=6),
        ),
    ]
