# Generated by Django 3.2 on 2021-05-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0014_auto_20210526_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='Candidate_present',
            field=models.CharField(choices=[('U', 'Unknown'), ('Y', 'Yes'), ('N', 'No')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='calendar',
            name='Worker_present',
            field=models.CharField(choices=[('U', 'Unknown'), ('Y', 'Yes'), ('N', 'No')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Hired',
            field=models.CharField(choices=[('2', 'In process'), ('P', 'Yes'), ('N', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Sex',
            field=models.CharField(choices=[('U', 'Unsure'), ('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Stage',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='', max_length=1),
        ),
    ]
